# Generated by Django 5.0.1 on 2024-05-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('energy_intake', models.IntegerField()),
                ('existing_medical_conditions', models.TextField()),
            ],
        ),
    ]
