# Generated by Django 5.0.3 on 2024-05-26 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionApp', '0004_fooditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyIntakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('daily_intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='NutritionApp.dailyintake')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NutritionApp.fooditem')),
            ],
        ),
    ]
