# Generated by Django 5.0.1 on 2024-06-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionApp', '0005_dailyintake_dailyintakeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomededIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(max_length=100)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('total_protein', models.FloatField()),
                ('total_carbohydrates', models.FloatField()),
                ('total_fat', models.FloatField()),
            ],
        ),
    ]
